Repository AcneLog/AcneLog_web, pull requests merged in 2025-07, with the labels that each got.

#19 🔀feat/result [아크네진단 결과화면 구현]
  src/pages/diagnosis/Diagnosis.tsx
  src/pages/diagnosis/Result.styles.ts
  src/pages/diagnosis/Result.tsx
  src/pages/diagnosis/resultDummyData.ts
  src/routes/Router.tsx
Labels: ✨feat, 조성아

#23 🔀fix/detail [아크네진단 결과 페이지, 피플즈로그 상세페이지, 마이로그 상세페이지 스타일링 및 오류 수정]
  package-lock.json
  package.json
  src/components/Header/Header.tsx
  src/pages/MyLog/MyLogDetail.styles.ts
  src/pages/MyLog/MyLogDetail.tsx
  src/pages/MyLog/MyLogDetailDummyData.ts
  src/pages/PeoplesLog/PeoplesLogDetail.styles.ts
  src/pages/PeoplesLog/PeoplesLogDetail.tsx
  src/pages/PeoplesLog/peoplesLogDetailDummyData.ts
  src/pages/diagnosis/Diagnosis.tsx
  src/pages/diagnosis/Result.styles.ts
  src/pages/diagnosis/Result.tsx
  src/routes/Router.tsx
Labels: 🛠️fix, 조성아

#25 🔀 feat/skin [ 나의 피부 타입 진단하기 화면, Not found 화면 스타일링 ]
  src/pages/NotFound.tsx
  src/pages/SkinDiagnosis/SkinDiagnosis.styles.ts
  src/pages/SkinDiagnosis/SkinDiagnosis.tsx
  src/pages/SkinDiagnosis/SkinDiagnosisResult.tsx
Labels: ✨feat, 이한슬
